### ISSUE TITLE
Add object construction expression

### ISSUE THREAD

**Issue by chocobo333** [chocobo333/regino#13]
Currently, there is  no way to create object types directly.
So, we need to add the following syntax to the object construction expression
```
T(field1: value1, field2: value2, ..., fieldN: valueN)
```
where `T` is object type name.

An example is bellow:
```
type
    Vector2 = object
        x: float
        y: float
let a = Vector2(x: 3, y: 4.5)
```

**Comment by Unit112358** [comment]
I added.
